/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Clock_2.h"
#include "MIDI1_UART.h"
#include "MIDI2_UART.h"
#include "Clock_1.h"
#include "USB.h"
#include "USB_audio.h"
#include "USB_cdc.h"
#include "USB_hid.h"
#include "USB_midi.h"
#include "USB_pvt.h"
#include "CharLCD_I2C.h"
#include "ADC_MIC.h"
#include "MIC_IN_aliases.h"
#include "MIC_IN.h"
#include "MIC_GND_aliases.h"
#include "MIC_GND.h"
#include "TIMER_SAMPLERATE.h"
#include "isr_1.h"
#include "ADC_UI.h"
#include "TIMER_UI.h"
#include "UI_isr.h"
#include "POT_IN_KEY_aliases.h"
#include "POT_IN_KEY.h"
#include "POT_IN_SCALE_aliases.h"
#include "POT_IN_SCALE.h"
#include "UART_MIDITX.h"
#include "SDA_aliases.h"
#include "SDA.h"
#include "SCL_aliases.h"
#include "SCL.h"
#include "I2C_CharLCD.h"
#include "I2C_CharLCD_PVT.h"
#include "POT_IN_HYST_aliases.h"
#include "POT_IN_HYST.h"
#include "POT_IN_VELO_aliases.h"
#include "POT_IN_VELO.h"
#include "POT_IN_NOISEGATE_aliases.h"
#include "POT_IN_NOISEGATE.h"
#include "Sleep_isr.h"
#include "SleepTimer.h"
#include "USB_Dm_aliases.h"
#include "USB_Dm.h"
#include "USB_Dp_aliases.h"
#include "USB_Dp.h"
#include "ADC_MIC_IRQ.h"
#include "ADC_MIC_theACLK.h"
#include "ADC_UI_SAR.h"
#include "ADC_UI_IntClock.h"
#include "ADC_UI_TempBuf_dma.h"
#include "ADC_UI_FinalBuf_dma.h"
#include "ADC_UI_IRQ.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

