/*******************************************************************************
* FILENAME: project.h
* 
* PSoC Creator  3.2 SP1
*
* DESCRIPTION:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC_SAR_1.h"
#include "LCD.h"
#include "MIC_IN_aliases.h"
#include "MIC_IN.h"
#include "Timer_1.h"
#include "isr_1.h"
#include "SDCard.h"
#include "MIC_GND_aliases.h"
#include "MIC_GND.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "SDCard_SPI0.h"
#include "SDCard_SPI0_PVT.h"
#include "SDCard_mosi0_aliases.h"
#include "SDCard_mosi0.h"
#include "SDCard_Clock_1.h"
#include "SDCard_miso0_aliases.h"
#include "SDCard_miso0.h"
#include "SDCard_sclk0_aliases.h"
#include "SDCard_sclk0.h"
#include "SDCard_SPI0_CS_aliases.h"
#include "SDCard_SPI0_CS.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

